### ISSUE TITLE
Plugin should not panic on error during publishing to Influx.

### ISSUE THREAD

**Issue by geauxvirtual** [intelsdi-x/snap-plugin-publisher-influxdb#10]

**Comment by katarzyna-z** [comment]
@geauxvirtual Do you know whether this issue still exist?

**Comment by sandlbn** [comment]
@katarzyna-z  yes it exist I tested even with ulimit -n 10000. After few hours influx plugin died.

**Comment by lynxbat** [comment]
This is fixed by #61
