### ISSUE TITLE
Latest publisher v21 release after loaded states it's v20

### ISSUE THREAD

**Issue by tnachen** [intelsdi-x/snap-plugin-publisher-influxdb#123]
After downloading and loading the publisher, snaptel plugin list says:

NAME                             VERSION         TYPE            SIGNED          STATUS          LOADED TIME
influxdb                         20              publisher       false           loaded          Tue, 21 Mar 2017 17:15:24 UTC

**Comment by mkuculyma** [comment]
@tnachen, do you refer to the incorrect version number of the collector? If so, it has already been corrected to version 21.

**Comment by tnachen** [comment]
Thanks!
