### ISSUE TITLE
Influx collector fails when tag value contains json

### ISSUE THREAD

**Issue by tnachen** [intelsdi-x/snap-plugin-publisher-influxdb#131]
When collecting metrics with Tags, if Tag value is a JSON String (e.g: {"a": [ 1, 2, 3, 4] }, the publisher fails to write into Influx as Influx couldn't parse the message.

**Comment by katarzyna-z** [comment]
@tnachen Could provide more details about the issue? Which version of snapteld and InfluxDB do you use? Which collector do you use to collect metrics?

**Comment by katarzyna-z** [comment]
I would like to close based that I cannot reproduce that one. Please reopen this issue if you still need a help in this point.
