### ISSUE TITLE
HTTPS issue

### ISSUE THREAD

**Issue by LuizOz** [intelsdi-x/snap-plugin-publisher-influxdb#132]
Hello,

This PR #121 is not implemented with the skip-verify option, so the create or and the if exists, fails:

DEBU[2017-05-23T22:34:10Z] starting publisher job                        _module=scheduler-job block=run job-type=publisher plugin-config=map[user:{Value:aa} retention:{Value:autogen} precision:{Value:ns} database:{Value:snap} isMultiFields:{Value:true} scheme:{Value:https} skip-verify:{Value:true} host:{Value:192.168.0.2} password:{Value:aa} port:{Value:8086}] plugin-name=influxdb plugin-version=-1

DEBU[2017-05-23T22:34:10Z] time="2017-05-23T22:34:10Z" level=error msg="Post https://192.168.0.2:8086/query?q=CREATE+DATABASE+snap: x509: certificate signed by unknown authority" plugin-name=influxdb plugin-type=publisher plugin-version=22   _module=plugin-exec io=stderr plugin=influxdb

**Comment by katarzyna-z** [comment]
@LuizOz to have clear understanding, the issue exists only if someone wants to skip https certificate verification (`skip-verify` set on true), am I right?

**Comment by LuizOz** [comment]
@katarzyna-z yes.

Right now https with a invalid certificate doesn't work(even with the skip-verify), but with a valid one, should be ok.
