### ISSUE TITLE
Do you really want a .netrc published?

### ISSUE THREAD

**Issue by damm** [intelsdi-x/snap-plugin-publisher-influxdb#30]
https://github.com/intelsdi-x/snap-plugin-publisher-influxdb/blob/master/.netrc

I don't know off hand (as I didn't test) if these are valid; but I don't know if you want to publish your credentials however?

**Comment by Lactem** [comment]
Since https://github.com/intelsdi-x/snap/pull/579 was merged, you're probably right that netrc should be removed. I created a PR here: https://github.com/intelsdi-x/snap-plugin-publisher-influxdb/pull/31

**Comment by damm** [comment]
My security sense says yes.  Even a throw away account if your tests need that functionality; it  could break if someone tries to break the throw away account.

**Comment by geauxvirtual** [comment]
Resolved with #36.
