### ISSUE TITLE
Plugin publishes wrong timestamp to the InfluxDB 0.10

### ISSUE THREAD

**Issue by sandlbn** [intelsdi-x/snap-plugin-publisher-influxdb#41]
I tried to use InfluxDB 0.10 and all entries are stored with wrong date "1 January of 1970".
 1970-01-01T00:00:01.456154571Z . Attaching screenshot, with InfluxDB Query

[iolie@irild016 ~]$ ~/snap/opt/snap/bin/snapctl plugin list
NAME 		 VERSION 	 TYPE 		 SIGNED 	 STATUS 	 LOADED TIME
file 		 3 		 publisher 	 false 		 loaded 	 Mon, 22 Feb 2016 15:22:41 GMT
influx 		 9 		 publisher 	 false 		 loaded 	 Mon, 22 Feb 2016 15:22:41 GMT
passthru 	 1 		 processor 	 false 		 loaded 	 Mon, 22 Feb 2016 15:22:41 GMT
csl 		 1 		 collector 	 false 		 loaded 	 Mon, 22 Feb 2016 15:22:38 GMT
osv 		 2 		 collector 	 false 		 loaded 	 Mon, 22 Feb 2016 15:22:40 GMT

![influxdb](https://cloud.githubusercontent.com/assets/2578718/13223066/b9f9d360-d97a-11e5-9acd-87d0b12c90c3.png)

**Comment by katarzyna-z** [comment]
@sandlbn Please check if it works correctly and let me know.

**Comment by sandlbn** [comment]
It's working now. Thanks.
