### ISSUE TITLE
Better exception handling based on user experience on long write

### ISSUE THREAD

**Issue by mbbroberg** [intelsdi-x/snap-plugin-publisher-influxdb#47]
Notes from https://github.com/intelsdi-x/snap/issues/731 -
- @thomastaylor312 found that `err="NaN is an unsupported value for field value" plugin-name=influx plugin-type=publisher plugin-version=10 point=<nil>` caused a nil pointer reference and caused the plugin to panic. So a mixture of bad data and a hard to read log (it was all in byte arrays)
- @geauxvirtual notes that this brings up a valid point that `unexpected EOF` could be improved upon. While that may be an error message received, it just becomes noise and has little value in knowing exactly why the job failed.

**Comment by Alrim42** [comment]
To sum up:
- Plugin is no longer panicking. Updated medium test to cover NaN in field value. More details should have been presented too (like all logs from this plugin or steps how to reproduce this issue).

- Unable to reproduce this issue with given details. 
Similar issues in Snap:
-> [Task moved to disabled state when system becomes too busy](https://github.com/intelsdi-x/snap/issues/1268)
-> ["Unexpected EOF Error" when using Snap with influxdb container](https://github.com/intelsdi-x/snap/issues/1054)
