### ISSUE TITLE
float64 and int conflict

### ISSUE THREAD

**Issue by felipewd** [intelsdi-x/snap-plugin-publisher-influxdb#67]
When using the disk collector plugin with influx as publisher, I get the following error:

`Publish call error: {"error":"field type conflict: input field \"value\" on measurement \"intel/procfs/disk/merged_read\" is type float64, already exists as type integer"}`

Talking about on slack, @IRCody suggested that this could be a publisher issue.

I'm using on influx 0.13, with snap master, influx master and go 1.6.3.

If @intelsdi-x/plugin-maintainers could please take a look, that'd great.

**Comment by IRCody** [comment]
cc: @intelsdi-x/plugin-maintainers

**Comment by thomastaylor312** [comment]
I have seen this before. What happened when I had the problem was that I had written test data that was an int and then started gathering data that was a float. I had to drop the measurement and recreate it for it to work. Is there anything like that in the problem you are experiencing @felipewd?

**Comment by felipewd** [comment]
Hi Thomas, I'm not sure this is what I did.

I just created a new database, installed the disk collector plugin and added the following task-manifest:
`
{
    "version": 1,
    "schedule": {
        "type": "simple",
        "interval": "1s"
    },
    "workflow": {
        "collect": {
            "metrics": {
		    "/intel/procfs/disk/*/*": {}
            },
            "process": null,
	    "publish": [
		    {
			    "plugin_name": "influx"
		    }
	    ]
        }
    }
}
`

The first collects are fine, but a few seconds latter I got the error described above. Maybe it is what you said (writing data in int first), but if it is...that'd be plugin's fault, right?

**Comment by felipewd** [comment]
@intelsdi-x/plugin-maintaine

**Comment by thomastaylor312** [comment]
@felipewd That is probably the case. It could also be with how the procfs plugin sends the data. I will dig into it some more

**Comment by thomastaylor312** [comment]
This turned out to be a bug in the disk collector and was fixed with [this PR](https://github.com/intelsdi-x/snap-plugin-collector-disk/pull/13). I am closing this issue.
