### ISSUE TITLE
InfluxDB 1.0 incompatibility

### ISSUE THREAD

**Issue by zoltan** [intelsdi-x/snap-plugin-publisher-influxdb#77]
In InfluxDB 1.0 they renamed the default retention policy that gets generated on every database from "default" to "autogen".

The plugin still references "default" and since (as far as I can see in the code) this is not configurable it is simply unable to push any data to influx.

I'd suggest:
* make the retention policy name that is being used configurable
* change it to "autogen" from "default" as the default value

**Comment by herver** [comment]
Hi there, 

I will tackle this one as I'm also affected, will be my first contrib to the project !

**Comment by candysmurf** [comment]
@herver, when you submit your PR, please put fixes #72 & #77 in your comments. thanks.

**Comment by candysmurf** [comment]
this is resolved by @herver's PR.
