### ISSUE TITLE
config:password is not used

### ISSUE THREAD

**Issue by herver** [intelsdi-x/snap-plugin-publisher-influxdb#86]
**Snap version** (use `snapctl -v`): 0.17.0

**Environment**:
- **Cloud provider or hardware configuration**: KVM VMs
- **OS** (e.g. from /etc/os-release): Centos 7.2
- **Kernel** (e.g. `uname -a`): 3.10.0-327.36.1.el7.x86_64
- **Relevant tools** (e.g. plugins used with Snap): snap-plugin-publisher-influxdb
- **Others** (e.g. deploying with Ansible):

**What happened**:
 - Configured the InfluxDB publisher plugin to write with user and password (where they're different)
 - Doesn't work, authentication failure

**What you expected to happen**:
 - Connection to InfluxDB to work.

**Steps to reproduce it** (as minimally and precisely as possible):

1. Create an InfluxDB user where `user` != `password`
2. Configure the publish with correct `user` and `password`
3. Run the task

**Anything else do we need to know** (e.g. issue happens only occasionally):

I have pinpointed it to this line of code, probably a typo https://github.com/intelsdi-x/snap-plugin-publisher-influxdb/blob/master/influxdb/influxdb.go#L103

**Comment by herver** [comment]
PR is coming when I figure out how to test this propery...

**Comment by kindermoumoute** [comment]
I recommend you test with the last Snap version, today we fixed a bug that was preventing default rules to be applied for 1 month: https://github.com/intelsdi-x/snap/pull/1316
