### ISSUE TITLE
1.0 support and updated support matrix

### ISSUE THREAD

**Issue by IRCody** [intelsdi-x/snap-plugin-publisher-influxdb#97]
The support matrix in the [README](https://github.com/intelsdi-x/snap-plugin-publisher-influxdb/blob/master/README.md) doesn't mention the current version influxdb 1.0. I think we should update this to include the current release version (16) and the compatibility (or incompatibility)  with influxdb 1.0.

**Comment by marcin-krolik** [comment]
Support matrics updated with #99. I deprecated all old version of Snap and also left only officially supported InfluxDB containers.

**Comment by IzabellaRaulin** [comment]
Resolved by https://github.com/intelsdi-x/snap-plugin-publisher-influxdb/pull/99
